# Generated by Django 4.2 on 2023-05-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('photo', models.ImageField(upload_to='')),
                ('position', models.CharField(max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=11)),
                ('birthday', models.DateField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department')),
            ],
        ),
    ]
